### PR TITLE
NEPT-1150: Upgrade the blockquote design.

### PR DESCRIPTION
**Pull request by Fefaine**

### CODE REVIEW

**Comment by imanoleguskiza** [comment]
👍

**Comment by netlooker** [comment]
@Fefaine I've updated the branch with the latest changes and I've added <p> tag to align the implementation with the markup which is shown on the style guide. Let me know if you agree and we can go further with this ticket. The rest looks good.

**Comment by imanoleguskiza** [comment]
👍

**Comment by netlooker** [comment]
👍

**Pull request merged**
