### PR TITLE
Making development easier

### PR DESCRIPTION
**Pull request by kalinchernev**
@planctus I sometimes have to compare with your latest work on this repo, so i'm making starting the local dev and serve a bit easier. You will also be able to deploy with 1 command.

### CODE REVIEW

**Comment by drupol** [comment]
👍

**Comment by Fefaine** [comment]
:+1:

**Comment by planctus** [comment]
@kalinchernev, @Fefaine, @drupol, why would you want to merge this with master? shouldn't this be against the atomium epic branch? Sorry if i was not on this already, i though it was one of the pull requests that you were handling on your own... ;)

**Comment by kalinchernev** [comment]
@planctus it's just a helper for you, in terms of your style guide. It's giving you npm scripts to manage what you have via grunt in an easier way.
If you want it - take it, if you don't - close it.

**Pull request closed without merging**
